import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import { BsTools } from "react-icons/bs";
import { IoSearchSharp } from "react-icons/io5";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
        <nav className="flex bg-blue-500 px-5 py-2 items-center justify-between">
          <Link href={"/home"} className="flex">
                <BsTools color="white" size="30" className="mr-5"/>
                <h2 className="text-white text-2xl font-bold">EasyJob</h2>
          </Link>
          <div className="flex">
            <input type="text" className="m-4"/>
            <input type="text" className="m-4"/>
            <div className="flex justify-center items-center">
              <IoSearchSharp color="white" size="30" className="border p-1 rounded-md"/>
            </div>
          </div>
          <div className="flex px-2 py-1.5 border-2 text-sm rounded-md border-white text-white font-semibold">Log out</div>
        </nav>
        <div className="flex px-40 pt-10">
          {children}
        </div>
    </>
  );
}
